### ISSUE TITLE
How to use this with jsxImportSource?

### ISSUE THREAD

**Issue by Asoftyn** [ConnorJamesLow/texsaur#22]
Hi, i like this library as it helps me greatly.
However adding the jsx import to every file could possibly be avoided by using jsxImportSource in tsconfig to automatically import the needed jsx. 

Could there be support for this implemented? or if there already is support could an example of how to use the jsxImportSource?

**Comment by ConnorJamesLow** [comment]
Using `jsxImportSource` in TypeScript should be supported; the implementation may depend on the build system you are using. If you have one in mind, let me know - if it's one I'm familiar with, I may be able to add an example to this repository.

**Comment by Asoftyn** [comment]
I would be grateful if you could do that

**Comment by ConnorJamesLow** [comment]
Did a little research: I don't know whether `jsxImportSource` is the best route to solve your issue: most build tools provide plugins or OOTB support for injecting the import statement. [I've added an example for how to do this in Vite.](https://github.com/ConnorJamesLow/texsaur/tree/main/examples/vite-ts-project-jsx-inject) 

If you want to provide more information about your environment, I might be able to give you pointers or provide an additional example; for now, I'm closing this issue.

**Comment by Asoftyn** [comment]
Hi its me again, Thank you for what you did last time, It seems like they gonna depricate the jsxInject option in vite, i googled around a bit and im not quite sure how to fix this issue now. The tsconfig and vite config in the vite-ts-project-jsx-inject does not seem to work anymore?

I would be really greatful if you could help me a little bit. Thank, You.

**Comment by ConnorJamesLow** [comment]
I investigated this further and found that Vite 4+ correctly adopts tsconfig settings so that `"jsx": "preserve"` now does what it is supposed to do; this breaks things since the browser doesn't know what to do with uncompiled jsx. I'm now working on a fix that will allow texsaur to work with `"jsx": "react-jsx"` tsconfig option. Once it's ready, the [vite-ts-project-jsx-inject](https://github.com/ConnorJamesLow/texsaur/tree/main/examples/vite-ts-project-jsx-inject) example will demonstrate this use-case.
